export const products = [
    {
        title: "Samsung S24 Ultra",
        price: 1200,
        oldPrice: 1320,
        stock: 5,
        category: "Samsung",
        available: true,
        urls: ["https://m.media-amazon.com/images/I/81vxWpPpgNL._SX679_.jpg", "https://m.media-amazon.com/images/I/71E-ptCgHcL._SX679_.jpg", "https://m.media-amazon.com/images/I/71JLhofuYJL._SX679_.jpg"],
        desc: "The latest flagship phone from Samsung with top-of-the-line features and performance.",
        info: ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        rating: 5
    },
    {
        "title": "Phones",
        "price": 250,
        "oldPrice": 274,
        "stock": 1,
        "category": "phone",
        "available": true,
        "urls": ["https://blog.unguess.io/hubfs/smartphone%20update-1.png", "https://i.ytimg.com/vi/GkFl3c-Zvx0/maxresdefault.jpg"],
        "desc": "An affordable smartphone option for those who need essential features without the high price tag.",
        "info": ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        "rating": 3
    },
    {
        "title": "iPhone 13",
        "price": 555,
        "oldPrice": 631,
        "stock": 7,
        "category": "Apple",
        "available": true,
        "urls": ["https://m.media-amazon.com/images/I/71Gu0e-vdNL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/617TKRByBpL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/81ANqRSTvmL._AC_SX679_.jpg"],
        "desc": "Apple's iPhone 13 offers a great balance of performance and price, with all the features you need.",
        "info": ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        "rating": 4
    },
    {
        title: "MacBook Pro",
        price: 999,
        oldPrice: 1230,
        stock: 3,
        category: "Apple",
        available: true,
        urls: ["https://m.media-amazon.com/images/I/61CHqS31PiL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/71bSZAYcsbL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/810RmaVJvtL._AC_SX522_.jpg"],
        desc: "A powerful laptop from Apple, perfect for professionals and power users.",
        info: ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        rating: 4
    },
    {
        title: "Samsung Galaxy Tab S9",
        price: 400,
        oldPrice: 450,
        stock: 10,
        category: "Samsung",
        available: true,
        urls: ["https://m.media-amazon.com/images/I/61d46oYQgdL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/61NTjkCP3vL._AC_SX466_.jpg"],
        desc: "Samsung's latest tablet offering with a sleek design and powerful features.",
        info: ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        rating: 3
    },
    {
        title: "Sony PlayStation 5",
        price: 500,
        oldPrice: 550,
        stock: 6,
        category: "Gaming",
        available: true,
        urls: ["https://m.media-amazon.com/images/I/21pybROD6BL._SY300_SX300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/51v1iiwtHkL._SX522_.jpg"],
        desc: "The latest gaming console from Sony, delivering an immersive gaming experience.",
        info: ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        rating: 4
    },
    {
        title: "Nintendo Switch",
        price: 300,
        oldPrice: 350,
        stock: 15,
        category: "Gaming",
        available: true,
        urls: ["https://m.media-amazon.com/images/I/41S2ZmCRO9L._SY300_SX300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/61Vy4+0XqJL._SX522_.jpg"],
        desc: "A versatile gaming console that can be used at home or on the go.",
        info: ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        rating: 3
    },
    {
        title: "Dell XPS 13",
        price: 1200,
        oldPrice: 1300,
        stock: 4,
        category: "Computers",
        available: true,
        urls: ["https://m.media-amazon.com/images/I/71Ir4cW5GNL.__AC_SY300_SX300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/61-NAS2Y-3L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/61No0-SXL8L._AC_SX679_.jpg"],
        desc: "Dell's XPS 13 is a high-end laptop with a beautiful display and top-tier performance.",
        info: ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        rating: 5
    },
    {
        title: "HP Spectre x360",
        price: 1100,
        oldPrice: 1250,
        stock: 2,
        category: "Computers",
        available: true,
        urls: ["https://m.media-amazon.com/images/I/61wdZ89-JWL.__AC_SY300_SX300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/613hlvL2lHL._AC_SX466_.jpg", "https://m.media-amazon.com/images/I/5171HN86xqL._AC_SX466_.jpg"],
        desc: "A premium 2-in-1 laptop from HP, offering flexibility and power in a sleek design.",
        info: ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        rating: 5
    },
    {
        title: "Microsoft Surface Pro",
        price: 1000,
        oldPrice: 1150,
        stock: 5,
        category: "Computers",
        available: true,
        urls: ["https://m.media-amazon.com/images/I/515nMh4oT9S._AC_SX466_.jpg", "https://m.media-amazon.com/images/I/618+M+0QsdL._AC_SX466_.jpg", "https://m.media-amazon.com/images/I/51TyBSK8qJL._AC_SX466_.jpg"],
        desc: "A powerful and versatile tablet-laptop hybrid from Microsoft.",
        info: ["1. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "3. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "4. Lorem ipsum dolor sit amet consectetur adipisicing elit."],
        rating: 4
    }
]